# FROM ubuntu
# ENTRYPOINT [“echo”, “Hello World”]

# docker build -t image-name .
# docker run image-name
# docker run image-name uname - not overridden

FROM almalinux:9
CMD [ "google.com" ]
ENTRYPOINT [ "ping","-c5" ]



