# FROM almalinux:9
# RUN mkdir /app
# WORKDIR /app 
# #setup the pwd
# RUN pwd
# CMD ["sleep","100"]


FROM almalinux:9
WORKDIR /dir1
WORKDIR dir2
WORKDIR dir3
ENTRYPOINT [ "pwd" ]
CMD ["sleep","100"]