# FROM almalinux:9
# RUN dnf install nginx -y
# CMD ["nginx","-g","daemon off;"]

FROM ubuntu
CMD [“echo”, “Hello World”]

# docker build -t image-name .
# docker run image-name
# docker run image-name uname - overridden